version: "3.9"

services:
  db:
    image: docker.io/library/postgres:16
    container_name: phoenix_db
    environment:
      POSTGRES_DB: phoenix_and_pepper
      POSTGRES_USER: phoenix
      POSTGRES_PASSWORD: pepper
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  metabase:
    image: docker.io/metabase/metabase:latest
    container_name: phoenix_metabase
    ports:
        - "3000:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: phoenix
      MB_DB_PASS: pepper
      MB_DB_HOST: host.containers.internal
    depends_on:
        - db

volumes:
  pgdata:
